{{- if and .Values.auth.rbac.enabled (not .Values.auth.rbac.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}-auth
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.rbac.passwordKey }}: {{ .Values.auth.rbac.rootPassword | b64enc | quote }}
{{- end }}
