apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.etcd.peerPort }}
      targetPort: peer
      name: peer
    - port: {{ .Values.etcd.clientPort }}
      targetPort: client
      name: client
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: client
      name: client
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
