{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.password" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  {{ .Values.auth.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
