{{- if and .Values.flower.basicAuth.enabled (not .Values.flower.basicAuth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flower.fullname" . }}-auth
  labels:
    {{- include "flower.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.flower.basicAuth.username | b64enc | quote }}
  password: {{ .Values.flower.basicAuth.password | b64enc | quote }}
{{- end }}
