{{- if and .Values.flower.basicAuth.enabled (not .Values.flower.basicAuth.existingSecret) -}}
{{- if or (not .Values.flower.basicAuth.username) (not .Values.flower.basicAuth.password) }}
{{- fail "When flower.basicAuth.enabled is true and flower.basicAuth.existingSecret is not set, both flower.basicAuth.username and flower.basicAuth.password must be provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flower.fullname" . }}-auth
  labels:
    {{- include "flower.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.flower.basicAuth.username | b64enc | quote }}
  password: {{ .Values.flower.basicAuth.password | b64enc | quote }}
{{- end }}
