apiVersion: v2
name: etcd
description: A Helm chart for deploying Etcd with High Availability (HA)
type: application
version: 0.1.0
appVersion: "3.5.10-0"
keywords:
  - etcd
  - ha
  - kv-store
home: https://github.com/onlinejudge95/helm-charts
sources:
  - https://github.com/etcd-io/etcd
maintainers:
  - name: onlinejudge95
    email: onlinejudge95@gmail.com
